dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "node"

env:
  - CURRENT_TAG="$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

cache:
  directories:
    - node_modules

before_deploy:
  - npm run build
  # https://docs.travis-ci.com/user/deployment/releases
  - if [ "$TRAVIS_BRANCH" == master ]; then
      git config --local user.name "Marcos Vinícius Rubido";
      git config --local user.email "github@marcosvrs.com";
      git tag "$CURRENT_TAG";
      echo "Created tag $CURRENT_TAG";
    fi

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "KnyoVtnPJzYZ2t3FD8lbKEY/XMlkqXonWeEof3cFPwKjsstyi63gCAaLt5TeTPYF9mIu5eSs9hkpCDjHXD5VmpUC3WZ2EQ2zxtH/vIQ1pMAjOJCXUWETpBjS1oiPNZPMMsxeHvLQzrFaK1rPxFdx1rP9VDdizTJehOP/l2qeMC/zcY6fa2j3GZPtJcKf62glkb8nNXLN6apRKurqYEVWmz5j6uEfUWChi7HVef7tEXS7iZrPQQ23AxFmNfeccJ04RAMeDLWdrNZqWuLhXO1IqdXKLspJNFu/SYYE8Du/NjmzMA8EycDOHjdA4YRawgUkNLQdNpjpUyysQjukPyuTE8arm9Mm/3yZvmSF10D1Hnw2ZiN/MZfE8LOiISdICv/zX2jBJNSqcea/8NjqMUkJXTUmJnYLTTH4eFQwipiJ5L766C2XS3y+bx6vYC2byEvhzwqhptQHXU+Y+q9RfenFdm1/1BI3z6AyO0TQ0wH9e9IWeRL4V20wUR2DKtXuMmc54HhK34N8aNTfqZ3+Z4gI2tCmQrOnt1iPsIxNarw6+Uds1J8HrHGqwMh6L1jKoBydL0F6fMWiZ5VYzUG2Lsff24lkWqVlPXCMWNa2F19oA+cRQc26/ZyxXK2m+9V9kwQkYvb5Jrk7YzLD2nHPlSLiIT/78a+Umy2za1Jpc6ivd78="
    project: "develop"
    on:
      branch: develop
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "mF8LfCdwvfPxiAcsPPTdEbbqEjKh0NjdmrtLckMOtlfzziYlRYvTh0x8SwcBLSLwCxo+/Dr+oMEmNK38lNB9+lNk5RH31pak1XoKhm4+nDdbkHVBgW0Mrd6TQF1lI7q1G1+/NMPW1oyFPr7rWsY0o9GuiYcOh1PHZRwc8DAH/i3HlmD+Vi3ZMdQjrL92/wHZR6rYz7+I0J3hbKMMyrVTULy+ZOnkmXndg0MzB/z62nSQY8rd4bqyl2R1Gnn+PkLyBH9cdHWl16fVtmlevlV9KxmYOOUyBbRvIvJ/zFu8z0wGWCHnekMEfeCOAKBuZ54yxGTnJjFDaMVFtOPTb5SJX1MfJsKMQdUTFJQl6946/yXvhriuk+VnLbmZE0cbE92velcwVdbdhrrVCl7bzBCS6QyqwnBkFfhfzgEU7SGRo29/OLSBaRnBhYVvBRvvu9QmHaAIGN4qFADctFB3fcmG1++NdaEGJW++rWiI+Act6+6RqxA+vEF+oQAfPQP2k0+DYhWey+dI7Ky2myNGA8iI7hPk63uuA9UeeHQxEMXnPZByqJHuhKvHo3EJ2gxUgdDa7Zh4d0f8ISNcmyyyStbd+8IHL7XVanw06wsMjGYOg6vTuOs700nED1LonXyaT4lwVqtJ9AZ3d/UYjXCsHYkr+c+Y/EtyL1GM4Vl8NBZAAhc="
    on:
      tags: true
  - provider: releases
  # https://docs.travis-ci.com/user/github-oauth-scopes/#Travis-CI-for-Open-Source-Projectsg
    api_key:
      secure: "XX4TxlJPFEVl+mhmIBn5teKNnxrh26iXpWN1CEWHgbmQ9gvvxhAdiRxQWGQ5Xu364M/RccSWSICtfgoWYprLg9lHX8XweS1UOcmnKCW8FHHxZChStWXb3WQ/Xah4lMnjjFjv85cUFSJxZyA4WU03av9o/kg3OxvfaMdIVbGOHzViLsMHHyih51ZSMCvUBf5JTioj91a7lkiud8j35I6Evlbj61COiUGZN9LsPqQm9lhHKr/GKzc/0MMjMt2H91byzKDxjfyDzQZ+gM4CCQdilfUY4pOHKYJ6wb3gZY4XH+mAOOcjiMBxm/jJa4M//o2TPEnLMe30HQs4ot4ISsEuc7wJEgwIs5HQsrguNsmg93JMM3blNWN8ak+YVZwOJHq0XvG8Uc3f8avqcRfBnCZcEGZvxED7YuJ/xmlqJb5wCnk84BkwVUBftWYclpuGbQLsfLlr9L7CQ1EkBZlfeBLp9Kraie/i/yRBDSA+EDPIkz86GrmtVpEuLukM1x4QXKcAtOcinml2GdhMyA1TxNu3129vrL7dKO0q9iml7gvyGah4/aF+UG2JWphWRQqJ146T2f55M2D/HT1q0OmEK0uS5XXiK5FVGkdCQrxcPfkwGFtkBHNWjmWWn4Lg4FHy/d8jBkw9Ccm/06NZYvGQwdW99iAmfSJYxOi8AbuQ1cEqcSY="
    on:
      branch: master